### ISSUE TITLE
Abstract Factory is missing in Abstract Factory Implementation

### ISSUE THREAD

**Issue by imrenagi** [girikuncoro/go-design-pattern#1]
Implementation of Abstract Factory in this file https://github.com/girikuncoro/go-design-pattern/blob/master/abstract-factory/abstract-factory.go is a bit wrong.

Abstract factory design pattern needs a class that will be used to create an instance of a factory. So, assume that I have 2 car factories named `Toyota Factory` and `Mazda Factory` which both implements `ManufactureInterface`, then I need to have a abstract factory that can create those two factories, assumed it's called `CarManufactureFactory`

```
public class CarManufactureFactory {

  public ManufactureInterface createManufacture(int type) {
    if (type == 1) {
      return new ToyotaFactory();
    } else {
      return new MazdaFactory();    
  }
}

```

In your case, you directly create the instance of the factories without using the abstract factory:
```
mazdaFactory := &MazdaFactory{}
toyotaFactory := &ToyotaFactory{}
```
This needs to be generated by an abstract factory instead.

nb: Sorry I dont know GO-lang, so i use java instead 🤣

**Comment by girikuncoro** [comment]
Good point, basically I just need another `FactoryProducer` class to abstract the Factory classes. I would argue this is using "factory method" to instantiate my factory classes, not the idea of abstract factory itself. The main idea of abstract factory is on the family creation:

```
mazdaPickup := mazdaFactory.CreatePickupTruck()
mazdaSport := mazdaFactory.CreateSportCar()
toyotaPickup := toyotaFactory.CreatePickupTruck()
toyotaSport := toyotaFactory.CreateSportCar()
```

I'll made an improvement
